# Generated by Django 5.2 on 2025-04-11 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='Company',
        ),
        migrations.AlterModelTable(
            name='vacancy',
            table='Vacancy',
        ),
    ]
